$(document).ready(function(){
    $(window).resize(function(){
        obj=$("body");
        lnum=obj[0].offsetWidth;
        $(".btn[data-id='logout']").css({"left":lnum-120});
    })
    $(".hd_panel").click(function(){
        obj=$("body");
        lnum=obj[0].offsetWidth;
        $(".btn[data-id='logout']").css({"left":lnum-120});
    })
    $(".btn[data-id='logout']").click(function(){
        document.location="?logout=true";
    }
    )
    $(".mitem").click(function(){
        lat=$(this).attr("data-item");
        document.location="?do="+lat;
    })
    $(window).resize();
})