<?php
  $do="docsa";
  if(isset($_GET["do"]))$_SESSION['do']=$_GET["do"];
  if(isset($_SESSION['do']))$do=$_SESSION['do'];
  if(($do=='doc')AND(!isset($_GET["item"]))){
      $do="docsa";
  }
  $do=strtolower($do);
  if(($do=="users")or($do=="newuser")){
      if($user->role!=1)$do="docsa";
  }
  $do.=".tpl";
  require("header.tpl");
  require($do);
  require("footer.tpl");
?>
